# Generated by Django 4.1.7 on 2024-07-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='recar_category_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Категория из Рекар'),
        ),
    ]
