# Generated by Django 4.1.7 on 2023-11-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_type',
            field=models.IntegerField(choices=[(1, 'Супервизор'), (2, 'Сотрудник'), (3, 'Продавец'), (4, 'Клиент')], default=4),
        ),
    ]
