# Generated by Django 4.2.14 on 2024-09-30 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудник'},
        ),
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавец'},
        ),
        migrations.AlterModelOptions(
            name='supervisorprofile',
            options={'verbose_name': 'Админ', 'verbose_name_plural': 'Админы'},
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
