# Generated by Django 4.2.14 on 2024-09-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_employeeprofile_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='postcode',
        ),
    ]
