# Generated by Django 4.2.14 on 2024-11-21 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_address_user'),
        ('users', '0011_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='supervisorprofile',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='ClientProfile',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='SellerProfile',
        ),
        migrations.DeleteModel(
            name='SupervisorProfile',
        ),
    ]
