# Generated by Django 4.2.14 on 2024-11-21 11:49

from django.db import migrations, models
import users.models.User


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_employeeprofile_user_ptr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_type',
        ),
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(blank=True, default=users.models.User.gen_uuid, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='users.role', verbose_name='Роли'),
        ),
    ]
