# Generated by Django 4.2.14 on 2024-11-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_role_remove_user_profile_type_user_uuid_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', to='users.role', verbose_name='Роли'),
        ),
    ]
