# Generated by Django 4.2.14 on 2024-11-22 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_role_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
    ]
