# Generated by Django 4.2.14 on 2025-03-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_usercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(1, 'Активный'), (2, 'Удален')], default=1),
        ),
    ]
