# Generated by Django 4.1.7 on 2023-11-20 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Код')),
                ('price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Цена')),
                ('market_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='Рыночная цена')),
                ('status', models.CharField(choices=[(1, 'Необработан'), (2, 'В наличии'), (3, 'Зарезервирован'), (4, 'Продан'), (5, 'Удален')], max_length=255)),
                ('properties', models.CharField(blank=True, max_length=255, null=True, verbose_name='Свойства')),
                ('defect', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дефект')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование модификации')),
                ('capacity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Вместимость (объем мотора)')),
                ('power', models.IntegerField(blank=True, default=0, null=True, verbose_name='Мощность')),
                ('numberOfCycle', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество шин')),
                ('numberOfValves', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество клапанов')),
                ('vinCode', models.IntegerField(blank=True, default=0, null=True, verbose_name='Вин код')),
                ('axleConfiguration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.axleconfiguration', verbose_name='Тип оси')),
                ('bodyType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.bodytype', verbose_name='Тип кузова')),
                ('driveType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.drivetype', verbose_name='Тип вождения(руль)')),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.engine', verbose_name='Тип двигателя')),
                ('fuelType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.fueltype', verbose_name='Тип топлива')),
                ('gearType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.geartype', verbose_name='Тип кпп')),
                ('mileageType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.mileagetype', verbose_name='Тип пробега')),
                ('modelCar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.modelcar', verbose_name='Модель машины')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Тех характиристика автомобиля',
                'verbose_name_plural': 'Тех характиристики автомобиля',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ProductImage/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='product.product')),
            ],
            options={
                'verbose_name': 'Фото продукта',
                'verbose_name_plural': 'Фото продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Высота')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='Ширина')),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Длина')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Детали продукта',
                'verbose_name_plural': 'Детали продукта',
            },
        ),
    ]
