# Generated by Django 4.1.7 on 2023-04-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sdu',
            new_name='sku',
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('supplier', 'sku')},
        ),
    ]
