# Generated by Django 4.1.7 on 2023-11-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_price_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'Необработан'), (2, 'В наличии'), (3, 'Зарезервирован'), (4, 'Продан'), (5, 'Удален')], max_length=255),
        ),
    ]
