# Generated by Django 4.1.7 on 2023-03-29 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_historicalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct_prices',
            name='history',
        ),
        migrations.RemoveField(
            model_name='historicalproduct_prices',
            name='price',
        ),
        migrations.RemoveField(
            model_name='historicalproduct_prices',
            name='product',
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
        migrations.DeleteModel(
            name='HistoricalProduct_prices',
        ),
    ]
