# Generated by Django 4.1.7 on 2023-07-17 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockreceipt'),
        ('product', '0004_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.quality'),
        ),
    ]
