# Generated by Django 4.1.7 on 2023-03-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_historicalproduct_prices_history_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPrice',
        ),
    ]
