# Generated by Django 4.1.7 on 2023-11-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_price_alter_productdetail_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='product.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='productmodification',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modification', to='product.product', verbose_name='Продукт'),
        ),
    ]
