# Generated by Django 4.1.7 on 2023-11-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_modification'),
        ('product', '0007_alter_productdetail_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.modification'),
        ),
        migrations.DeleteModel(
            name='ProductModification',
        ),
    ]
