# Generated by Django 4.1.7 on 2023-11-24 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_remove_modification_mileagetype'),
        ('product', '0009_remove_product_price_price_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mileage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='mileageType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.mileagetype', verbose_name='Тип пробега'),
        ),
    ]
