# Generated by Django 4.1.7 on 2023-11-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'Необработан'), (2, 'В наличии'), (3, 'Зарезервирован'), (4, 'Продан'), (5, 'Удален')], default=1),
        ),
    ]
