# Generated by Django 4.1.7 on 2024-02-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_oemcodes'),
        ('product', '0013_product_category_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.ManyToManyField(blank=True, null=True, to='car.oemcodes'),
        ),
    ]
