# Generated by Django 4.1.7 on 2024-03-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
