# Generated by Django 4.1.7 on 2024-03-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_alter_price_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
