# Generated by Django 4.1.7 on 2024-07-18 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_price_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='warehouse',
        ),
    ]
