# Generated by Django 4.1.7 on 2024-07-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_product_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='Product ID')),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Импротированные данные о продукте',
                'verbose_name_plural': 'Импротированные данные о продукте',
            },
        ),
    ]
