# Generated by Django 4.2.14 on 2025-01-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_productview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productview',
            options={'verbose_name': 'Просмотр продукта', 'verbose_name_plural': 'Просмотры продукта'},
        ),
    ]
