# Generated by Django 4.2.14 on 2025-09-15 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_parent'),
        ('car', '0011_manufacturertype_image'),
        ('product', '0026_alter_productview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comment_qr',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий QR'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.ManyToManyField(blank=True, null=True, related_name='codes', to='car.oemcodes'),
        ),
    ]
