# Generated by Django 4.2.14 on 2025-12-26 18:47

from django.db import migrations


class Migration(migrations.Migration):
    """
    Добавляет оптимизированные индексы для таблицы eav_value.

    Эти индексы значительно ускоряют фильтрацию продуктов по EAV атрибутам,
    особенно при работе с большими объемами данных (100,000+ товаров).

    Ожидаемое улучшение: 10x быстрее для запросов с фильтрами по атрибутам.
    """

    dependencies = [
        ('product', '0027_alter_product_category'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            -- Индекс на entity_id (используется в WHERE entity_id = ...)
            CREATE INDEX IF NOT EXISTS eav_value_entity_id_idx
            ON eav_value (entity_id);

            -- Индекс на generic_value_id (используется в WHERE generic_value_id IN ...)
            CREATE INDEX IF NOT EXISTS eav_value_generic_value_id_idx
            ON eav_value (generic_value_id);

            -- Составной индекс для частых запросов (attribute_id, entity_id)
            CREATE INDEX IF NOT EXISTS eav_value_attr_entity_idx
            ON eav_value (attribute_id, entity_id);

            -- Составной индекс для фильтров по модели авто (attribute_id, generic_value_id)
            CREATE INDEX IF NOT EXISTS eav_value_attr_generic_idx
            ON eav_value (attribute_id, generic_value_id);
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS eav_value_entity_id_idx;
            DROP INDEX IF EXISTS eav_value_generic_value_id_idx;
            DROP INDEX IF EXISTS eav_value_attr_entity_idx;
            DROP INDEX IF EXISTS eav_value_attr_generic_idx;
            """
        )
    ]
