# Generated by Django 4.2.14 on 2026-06-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_product_comment_qr_alter_product_category_and_more'),
        ('product', '0028_add_eav_value_indexes'),
    ]

    operations = [
    ]
