# Generated by Django 4.1.7 on 2023-11-12 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страна',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('uid', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handbook.country')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('address1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес Доп')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('apartment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Квартира')),
                ('floor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Этаж')),
                ('entrance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подъезд')),
                ('building', models.CharField(blank=True, max_length=255, null=True, verbose_name='Дом')),
                ('coords', models.JSONField(blank=True, max_length=255, null=True, verbose_name='Кордината')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='handbook.city')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адрес',
            },
        ),
    ]
