# Generated by Django 4.1.7 on 2023-11-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
