# Generated by Django 4.1.7 on 2024-03-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_parent'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='products_category',
            field=models.ManyToManyField(blank=True, null=True, to='category.category'),
        ),
    ]
