# Generated by Django 4.1.7 on 2024-07-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_warehouse_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='min_stock_level',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.warehouse'),
        ),
    ]
