# Generated by Django 4.1.7 on 2024-07-18 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_stock_min_stock_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
