# Generated by Django 4.1.7 on 2023-04-26 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_stock_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockhistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='stockhistory',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stock.stock'),
            preserve_default=False,
        ),
    ]
