# Generated by Django 4.1.7 on 2024-07-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_stock_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse'),
        ),
    ]
