# Generated by Django 4.1.7 on 2024-07-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stockmovement_delete_stockreceipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'verbose_name': 'Движение остатков', 'verbose_name_plural': 'Движение остатков'},
        ),
    ]
