# Generated by Django 4.2.14 on 2024-08-05 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_product_status'),
        ('stock', '0007_alter_stockmovement_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='product.product'),
        ),
        migrations.DeleteModel(
            name='StockHistory',
        ),
    ]
