# Generated by Django 4.2.14 on 2024-08-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_stock_unique_together_alter_stock_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.quality'),
        ),
    ]
