# Generated by Django 4.2.14 on 2024-08-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_stockmovement_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseDrafts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_id', models.IntegerField()),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Импортированные данные со склада',
                'verbose_name_plural': 'Импортированные данные со склада',
            },
        ),
    ]
