# Generated by Django 4.2.14 on 2024-09-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_stock_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ('-created_at',), 'verbose_name': 'Движение остатков', 'verbose_name_plural': 'Движение остатков'},
        ),
    ]
