# Generated by Django 4.2.14 on 2025-03-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_alter_stockmovement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='status',
            field=models.IntegerField(choices=[(1, 'Активный'), (2, 'Удален')], default=1),
        ),
    ]
