# Generated by Django 4.1.7 on 2023-04-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_history_edits_alter_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='edits',
            field=models.JSONField(default=dict),
        ),
    ]
