# Generated by Django 4.1.7 on 2023-11-21 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='history',
            name='history_his_instanc_e7691b_idx',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='instance',
            new_name='content_type',
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['content_type', 'object_id'], name='history_his_content_774c23_idx'),
        ),
    ]
