# Generated by Django 4.1.7 on 2023-04-26 06:27

import apps.order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(blank=True, default=apps.order.models.default_uuid, unique=True),
        ),
    ]
