# Generated by Django 4.1.7 on 2023-11-20 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.quality'),
        ),
    ]
