# Generated by Django 4.1.7 on 2024-02-26 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('order', '0004_remove_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.IntegerField(choices=[(1, 'Самовывоз'), (2, 'Перевозка')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Наличные'), (2, 'Интернет оплата'), (3, 'Картой')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse'),
            preserve_default=False,
        ),
    ]
