# Generated by Django 4.2.14 on 2024-09-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('order', '0007_remove_orderitem_quality_order_address_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='address.address', verbose_name='Адрес доставки'),
        ),
    ]
