# Generated by Django 4.2.14 on 2024-11-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='order.order'),
        ),
    ]
