# Generated by Django 4.2.14 on 2024-11-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_refund_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportOrderData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Импротированные заказы',
                'verbose_name_plural': 'Импротированные заказы',
            },
        ),
    ]
