# Generated by Django 4.2.14 on 2024-11-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_importorderdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_returning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'В процессе'), (2, 'Завершен'), (3, 'Отменен'), (4, 'Возвращен')], default=1),
        ),
    ]
