# Generated by Django 4.2.14 on 2024-12-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_orderitem_is_returning_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.IntegerField(choices=[(1, 'Наличные'), (2, 'Интернет оплата'), (3, 'Предоплата')], default=1),
        ),
    ]
