# Generated by Django 4.2.14 on 2025-03-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'В процессе'), (2, 'Завершен'), (3, 'Отменен'), (4, 'Возвращен'), (5, 'Удален')], default=1),
        ),
    ]
