# Generated by Django 4.1.7 on 2023-11-21 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование модификации')),
                ('capacity', models.IntegerField(blank=True, default=0, null=True, verbose_name='Вместимость (объем мотора)')),
                ('power', models.IntegerField(blank=True, default=0, null=True, verbose_name='Мощность')),
                ('numberOfCycle', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество шин')),
                ('numberOfValves', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество клапанов')),
                ('vinCode', models.IntegerField(blank=True, default=0, null=True, verbose_name='Вин код')),
                ('axleConfiguration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.axleconfiguration', verbose_name='Тип оси')),
                ('bodyType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.bodytype', verbose_name='Тип кузова')),
                ('driveType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.drivetype', verbose_name='Тип вождения(руль)')),
                ('engine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.engine', verbose_name='Тип двигателя')),
                ('fuelType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.fueltype', verbose_name='Тип топлива')),
                ('gearType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.geartype', verbose_name='Тип кпп')),
                ('mileageType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.mileagetype', verbose_name='Тип пробега')),
                ('modelCar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.modelcar', verbose_name='Модель машины')),
            ],
            options={
                'verbose_name': 'Тех характиристика автомобиля',
                'verbose_name_plural': 'Тех характиристики автомобиля',
            },
        ),
    ]
