# Generated by Django 4.1.7 on 2023-11-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_modelcar_options_alter_modelcar_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='capacity',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Вместимость (объем мотора)'),
        ),
    ]
