# Generated by Django 4.1.7 on 2023-11-24 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_modification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='modification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engine', to='car.modification'),
        ),
    ]
