# Generated by Django 4.1.7 on 2023-11-24 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_engine_modification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='mileageType',
        ),
    ]
