# Generated by Django 4.1.7 on 2024-02-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_remove_modification_mileagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OemCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'OEM коды',
                'verbose_name_plural': 'OEM коды',
            },
        ),
    ]
