# Generated by Django 4.2.14 on 2024-08-08 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_oemcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='engineDisplacement',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Вместимость'),
        ),
        migrations.AddField(
            model_name='modification',
            name='steeringType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.steeringtype', verbose_name='Тип рулевого управления'),
        ),
    ]
