# Generated by Django 4.2.14 on 2024-08-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_modification_enginedisplacement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModificationDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='Product ID')),
                ('data', models.JSONField()),
            ],
            options={
                'verbose_name': 'Импортированные данные о модификации',
                'verbose_name_plural': 'Импортированные данные о модификации',
            },
        ),
    ]
