# Generated by Django 4.2.14 on 2024-08-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_modificationdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturertype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Manufacturers/'),
        ),
    ]
